services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=skills'
      - 'MONGO_INITDB_ROOT_PASSWORD=admin'
      - 'MONGO_INITDB_ROOT_USERNAME=password'
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
