services:
  mongodb:
    image: 'mongo:latest'
    environment:
        MONGO_INITDB_DATABASE: skills
        MONGO_INITDB_ROOT_USERNAME: test
        MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

